openapi: 3.0.3
info:
  title: Sample API Documents
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1.0.0
  - url: https://api-dev.example.com/api/v1.0.0
  - url: https://api.example.com/api/v1.0.0
paths:
  /users/{id}:
    get:
      operationId: GetUser
      description: Get user
      tags:
        - users
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    patch:
      operationId: UpdateUser
      description: Update user
      tags:
        - users
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: User name
                  example: "John Doe"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users:
    post:
      operationId: CreateUser
      description: Create user
      tags:
        - users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
              properties:
                name:
                  type: string
                  description: User name
                  example: "John Doe"
                email:
                  type: string
                  description: Email address
                  example: "doe.john@example.com"
      responses:
        '201':
          description: "Created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - email
        - created_at
        - updated_at
      properties:
        id:
          type: string
          description: User ID
          example: "01FH7JYRSE288VKAKXWAASMF"
        name:
          type: string
          description: User name
          example: "John Doe"
        email:
          type: string
          description: Email address
          example: "doe.john@example.com"